# Generated by Django 4.2.4 on 2023-08-16 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='ordering',
            field=models.IntegerField(unique=True),
        ),
    ]
